name: bigbox
description: "Big Box Copyright."
publish_to: 'none'
version: 1.0.4+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  styled_widget: ^0.4.1
  intl: ^0.19.0
  loading_animation_widget: ^1.2.1
  flutter_svg: ^2.0.10+1
  flutter_otp_text_field: ^1.1.3+2
  top_snackbar_flutter: ^3.1.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  lottie: ^3.1.2
  permission_handler: ^11.3.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-beta.2
  camera: ^0.11.0
  path_provider: ^2.1.3
  path: ^1.9.0
  carousel_slider: ^4.2.1
  firebase_auth: ^4.19.5
  flutter_local_notifications: ^17.1.2
  firebase_analytics: ^10.10.5
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  animated_snack_bar: ^0.4.0
  image_gallery_saver: ^2.0.3
  charset_converter: ^2.2.1
  bottom_picker: ^2.8.0
  flutter_slidable: ^3.1.1
  url_launcher: ^6.3.0
  html_editor_enhanced: ^2.5.1
  file_picker: ^5.5.0
  flex_color_picker: ^3.4.1
  flutter_inappwebview: ^5.8.0
  flutter_keyboard_visibility: ^5.4.1
  lints: ^3.0.0
  meta: ^1.11.0
  numberpicker: ^2.1.2
  pointer_interceptor: ^0.9.3+7
  visibility_detector: ^0.3.3
  html: ^0.15.4
  image_picker: ^1.1.2
  # esc_pos_utils: ^1.1.0
  # esc_pos_bluetooth: ^0.4.1
  ai_barcode_scanner: ^5.1.1+2 
  mobile_scanner: ^5.1.1
  bluetooth_print_plus: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo-white.png
    - assets/icons/
    - assets/images/